name: weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^9.0.0
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  intl: ^0.18.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  font_awesome_flutter: ^10.4.0
  modal_progress_hud_nsn: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - Assets/Images/

  fonts:
    - family: Russo One
      fonts:
        - asset: Assets/Fonts/Russo/RussoOne-Regular.ttf
    - family: Chakra Petch
      fonts:
        - asset: Assets/Fonts/Chakra_Petch/ChakraPetch-Light.ttf
          weight: 300
        - asset: Assets/Fonts/Chakra_Petch/ChakraPetch-Regular.ttf
          weight: 400
        - asset: Assets/Fonts/Chakra_Petch/ChakraPetch-SemiBold.ttf
          weight: 600
